# Copyright 2021 Canonical
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
#
options:
  kube-config:
    default: ""
    description: k8s config. If you're using microk8s, this should be the output of `microk8s config`.
    type: string
