# Copyright 2021 Canonical
# See LICENSE file for licensing details.
options:
  tls-secret-name:
    description: |
      The name of an existing Kubernetes secret that contains a TLS certificate and
      key to be used when serving the Kubernetes Dashboard. The secret can be of type
      `Opaque` or `kubernetes.io/tls` but must include the fields `tls.crt` and `tls.key`
      in its `data`.

      If this is not specified, the operator will automatically generate a self-signed
      certificate for use
    type: string
    default: ""
